### ISSUE TITLE
Can't connect with authentication

### ISSUE THREAD

**Issue by faliure** [joliveros/bitmex-websocket#11]
Hi,

In _bitmex_websocket.py:126 it should say:
  auth_header = [ ...
instead of 
  auth = [ ...

**Comment by SeanEstey** [comment]
This is still not patched as of July-26-2019

**Comment by faliure** [comment]
Thanks for the heads up. Just sent a Pull Request with the change.

**Comment by joliveros** [comment]
Hi,

sorry for the late reply. This should be fixed.
