### ISSUE TITLE
Noob question ?

### ISSUE THREAD

**Issue by GrandadsJumper** [joliveros/bitmex-websocket#21]
Ive installed the module with pip, unsure what this next step is. I've tried running it in my terminal but get errors ?

(testbitmexcutomapis) C:\Users\User\testbitmexcutomapis>cp .env.example .env
'cp' is not recognized as an internal or external command,
operable program or batch file.

(testbitmexcutomapis) C:\Users\User\testbitmexcutomapis>source .env
'source' is not recognized as an internal or external command,
operable program or batch file.

**Comment by joliveros** [comment]
Hi @GrandadsJumper,
For windows you might want to try something like [this](https://www.windows-commandline.com/windows-copy-command-syntax-examples/).
